# Generated by Django 3.1.3 on 2020-12-04 20:06

import ZKH_App.months
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Обнолено')),
                ('month', models.PositiveIntegerField(choices=[(ZKH_App.months.Month['JANUARY'], 'Январь'), (ZKH_App.months.Month['FEBRUARY'], 'Февраль'), (ZKH_App.months.Month['MARCH'], 'Март'), (ZKH_App.months.Month['APRIL'], 'Апрель'), (ZKH_App.months.Month['MAY'], 'Май'), (ZKH_App.months.Month['JUNE'], 'Июнь'), (ZKH_App.months.Month['JULY'], 'Июль'), (ZKH_App.months.Month['AUGUST'], 'Август'), (ZKH_App.months.Month['SEPTEMBER'], 'Сентябрь'), (ZKH_App.months.Month['OCTOBER'], 'Октябрь'), (ZKH_App.months.Month['NOVEMBER'], 'Ноябрь'), (ZKH_App.months.Month['DECEMBER'], 'Декабрь')])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('value', models.PositiveIntegerField()),
                ('is_paid', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Дом')),
                ('flat_number', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Квартира')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Saldo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Обнолено')),
                ('month', models.PositiveIntegerField(choices=[(ZKH_App.months.Month['JANUARY'], 'Январь'), (ZKH_App.months.Month['FEBRUARY'], 'Февраль'), (ZKH_App.months.Month['MARCH'], 'Март'), (ZKH_App.months.Month['APRIL'], 'Апрель'), (ZKH_App.months.Month['MAY'], 'Май'), (ZKH_App.months.Month['JUNE'], 'Июнь'), (ZKH_App.months.Month['JULY'], 'Июль'), (ZKH_App.months.Month['AUGUST'], 'Август'), (ZKH_App.months.Month['SEPTEMBER'], 'Сентябрь'), (ZKH_App.months.Month['OCTOBER'], 'Октябрь'), (ZKH_App.months.Month['NOVEMBER'], 'Ноябрь'), (ZKH_App.months.Month['DECEMBER'], 'Декабрь')])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('value', models.PositiveIntegerField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.charge')),
            ],
            options={
                'verbose_name': 'Сальдо',
                'verbose_name_plural': 'Сальдо',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Обнолено')),
                ('month', models.PositiveIntegerField(choices=[(ZKH_App.months.Month['JANUARY'], 'Январь'), (ZKH_App.months.Month['FEBRUARY'], 'Февраль'), (ZKH_App.months.Month['MARCH'], 'Март'), (ZKH_App.months.Month['APRIL'], 'Апрель'), (ZKH_App.months.Month['MAY'], 'Май'), (ZKH_App.months.Month['JUNE'], 'Июнь'), (ZKH_App.months.Month['JULY'], 'Июль'), (ZKH_App.months.Month['AUGUST'], 'Август'), (ZKH_App.months.Month['SEPTEMBER'], 'Сентябрь'), (ZKH_App.months.Month['OCTOBER'], 'Октябрь'), (ZKH_App.months.Month['NOVEMBER'], 'Ноябрь'), (ZKH_App.months.Month['DECEMBER'], 'Декабрь')])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)])),
                ('value', models.PositiveIntegerField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.charge')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_number', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Номер контракта')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateField(auto_now=True, null=True, verbose_name='Обнолено')),
                ('bill_number', models.PositiveIntegerField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.flat')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
        migrations.AddField(
            model_name='charge',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.contract'),
        ),
    ]
