# Generated by Django 3.1.3 on 2020-12-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер контракта'),
        ),
    ]
