# Generated by Django 3.1.3 on 2020-12-04 21:46

import ZKH_App.months
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0002_auto_20201204_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='month',
            field=models.CharField(choices=[(ZKH_App.months.Month['JANUARY'], 'Январь'), (ZKH_App.months.Month['FEBRUARY'], 'Февраль'), (ZKH_App.months.Month['MARCH'], 'Март'), (ZKH_App.months.Month['APRIL'], 'Апрель'), (ZKH_App.months.Month['MAY'], 'Май'), (ZKH_App.months.Month['JUNE'], 'Июнь'), (ZKH_App.months.Month['JULY'], 'Июль'), (ZKH_App.months.Month['AUGUST'], 'Август'), (ZKH_App.months.Month['SEPTEMBER'], 'Сентябрь'), (ZKH_App.months.Month['OCTOBER'], 'Октябрь'), (ZKH_App.months.Month['NOVEMBER'], 'Ноябрь'), (ZKH_App.months.Month['DECEMBER'], 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.flat', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='bill_number',
            field=models.PositiveIntegerField(verbose_name='Номер счета'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.charge', verbose_name='Номер выставленного счета'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(choices=[(ZKH_App.months.Month['JANUARY'], 'Январь'), (ZKH_App.months.Month['FEBRUARY'], 'Февраль'), (ZKH_App.months.Month['MARCH'], 'Март'), (ZKH_App.months.Month['APRIL'], 'Апрель'), (ZKH_App.months.Month['MAY'], 'Май'), (ZKH_App.months.Month['JUNE'], 'Июнь'), (ZKH_App.months.Month['JULY'], 'Июль'), (ZKH_App.months.Month['AUGUST'], 'Август'), (ZKH_App.months.Month['SEPTEMBER'], 'Сентябрь'), (ZKH_App.months.Month['OCTOBER'], 'Октябрь'), (ZKH_App.months.Month['NOVEMBER'], 'Ноябрь'), (ZKH_App.months.Month['DECEMBER'], 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='month',
            field=models.CharField(choices=[(ZKH_App.months.Month['JANUARY'], 'Январь'), (ZKH_App.months.Month['FEBRUARY'], 'Февраль'), (ZKH_App.months.Month['MARCH'], 'Март'), (ZKH_App.months.Month['APRIL'], 'Апрель'), (ZKH_App.months.Month['MAY'], 'Май'), (ZKH_App.months.Month['JUNE'], 'Июнь'), (ZKH_App.months.Month['JULY'], 'Июль'), (ZKH_App.months.Month['AUGUST'], 'Август'), (ZKH_App.months.Month['SEPTEMBER'], 'Сентябрь'), (ZKH_App.months.Month['OCTOBER'], 'Октябрь'), (ZKH_App.months.Month['NOVEMBER'], 'Ноябрь'), (ZKH_App.months.Month['DECEMBER'], 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='value',
            field=models.PositiveIntegerField(verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2020)], verbose_name='Год'),
        ),
    ]
