# Generated by Django 3.1.3 on 2020-12-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0003_auto_20201205_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='month',
            field=models.CharField(choices=[('Январь', 'January'), ('Февраль', 'February'), ('Март', 'March'), ('Апрель', 'April'), ('Май', 'May'), ('Июнь', 'June'), ('Июль', 'July'), ('Август', 'August'), ('Сентябрь', 'September'), ('Октябрь', 'October'), ('Ноябрь', 'November'), ('Декабрь', 'December')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(choices=[('Январь', 'January'), ('Февраль', 'February'), ('Март', 'March'), ('Апрель', 'April'), ('Май', 'May'), ('Июнь', 'June'), ('Июль', 'July'), ('Август', 'August'), ('Сентябрь', 'September'), ('Октябрь', 'October'), ('Ноябрь', 'November'), ('Декабрь', 'December')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='month',
            field=models.CharField(choices=[('Январь', 'January'), ('Февраль', 'February'), ('Март', 'March'), ('Апрель', 'April'), ('Май', 'May'), ('Июнь', 'June'), ('Июль', 'July'), ('Август', 'August'), ('Сентябрь', 'September'), ('Октябрь', 'October'), ('Ноябрь', 'November'), ('Декабрь', 'December')], max_length=20, verbose_name='Месяц'),
        ),
    ]
