# Generated by Django 3.1.3 on 2020-12-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0004_auto_20201205_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='id',
        ),
        migrations.AddField(
            model_name='charge',
            name='charge_number',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='Номер квитанции'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='saldo',
            name='month',
            field=models.CharField(choices=[('Январь', 'Январь'), ('Февраль', 'Февраль'), ('Март', 'Март'), ('Апрель', 'Апрель'), ('Май', 'Май'), ('Июнь', 'Июнь'), ('Июль', 'Июль'), ('Август', 'Август'), ('Сентябрь', 'Сентябрь'), ('Октябрь', 'Октябрь'), ('Ноябрь', 'Ноябрь'), ('Декабрь', 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
    ]
