# Generated by Django 3.1.3 on 2020-12-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0005_auto_20201205_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charge_number',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер квитанции'),
        ),
    ]
