# Generated by Django 3.1.3 on 2020-12-04 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0006_auto_20201205_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.contract', verbose_name='Номер контракта'),
        ),
    ]
