# Generated by Django 3.1.3 on 2020-12-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0007_auto_20201205_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=None, null=True, verbose_name='Время внесения платежа'),
        ),
    ]
