# Generated by Django 3.1.3 on 2020-12-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0008_auto_20201205_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время внесения платежа'),
        ),
    ]
