# Generated by Django 3.1.3 on 2020-12-04 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0009_auto_20201205_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='charge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.charge'),
        ),
    ]
