# Generated by Django 3.1.3 on 2020-12-05 01:31

import ZKH_App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0010_auto_20201205_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZKH_App.charge', validators=[ZKH_App.models.payment_validator], verbose_name='Номер выставленного счета'),
        ),
    ]
