# Generated by Django 3.1.3 on 2020-12-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0011_auto_20201205_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='id',
        ),
        migrations.AlterField(
            model_name='saldo',
            name='charge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ZKH_App.charge'),
        ),
    ]
