# Generated by Django 3.1.3 on 2020-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0012_auto_20201205_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saldo',
            name='value',
            field=models.IntegerField(verbose_name='Сумма'),
        ),
    ]
