# Generated by Django 3.1.3 on 2020-12-05 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0013_auto_20201205_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saldo',
            name='month',
        ),
        migrations.RemoveField(
            model_name='saldo',
            name='year',
        ),
    ]
