# Generated by Django 3.1.3 on 2020-12-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZKH_App', '0014_auto_20201205_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='value_with_saldo',
            field=models.IntegerField(default=0, verbose_name='Сумма с учетом сальдо'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='value',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма'),
        ),
    ]
